/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AnimatePresence: typeof import('motion/react')['AnimatePresence']
  const Suspense: typeof import('react')['Suspense']
  const clsx: typeof import('clsx')['clsx']
  const forwardRef: typeof import('react')['forwardRef']
  const motion: typeof import('motion/react')['motion']
  const useCallback: typeof import('react')['useCallback']
  const useEffect: typeof import('react')['useEffect']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useParams: typeof import('react-router-dom')['useParams']
  const useRef: typeof import('react')['useRef']
  const useRoutes: typeof import('react-router-dom')['useRoutes']
  const useState: typeof import('react')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
